subdir-ccflags-y += -Idrivers/marvell/marvell-telephony/include
subdir-ccflags-y += -DEXPORT_SYMTAB

obj-y += ccinetdev/

obj-y += cidatastub/

obj-y += cidatatty/

obj-y += cimodemtty/

obj-y += citty/

obj-y += cp_load/

obj-y += diag/

obj-y += errorhandler/

obj-y += hwmap/

obj-y += shmem/

obj-y += usim_event/
